"use client";

import type { ComponentType } from "react";
import {
  RevealButtonPreview,
  HoldButtonPreview,
  HoldConfirmButtonPreview,
  SlideToDetonatePreview,
  DoubtButtonPreview,
  CaptchaButtonPreview,
  CooldownButtonPreview,
  MorphStatusButtonPreview,
} from "./interaction";
import {
  BrutalButtonPreview,
  DitherButtonPreview,
  GlitchButtonPreview,
  EvilEyeButtonPreview,
  AquaButtonPreview,
  FrameButtonPreview,
  HighlightButtonPreview,
  ConfettiButtonPreview,
  AshBurstButtonPreview,
} from "./visual";
import {
  CommandButtonPreview,
  CopyButtonPreview,
  ClickPowerUpPreview,
  PillButtonPreview,
} from "./utility";
import {
  DemonicButtonPreview,
  ChromeButtonPreview,
  GridButtonPreview,
  MinimalButtonPreview,
  MoviePassButtonPreview,
  ShinyButtonPreview,
  StickyButtonPreview,
  ThreeDButtonPreview,
  TrollButtonPreview,
  DontPressButtonPreview,
} from "./simple";
import {
  StaticRevealButtonPreview,
  StaticHoldButtonPreview,
  StaticHoldConfirmButtonPreview,
  StaticSlideToDetonatePreview,
  StaticDoubtButtonPreview,
  StaticCaptchaButtonPreview,
  StaticCooldownButtonPreview,
  StaticMorphStatusButtonPreview,
  StaticBrutalButtonPreview,
  StaticDitherButtonPreview,
  StaticGlitchButtonPreview,
  StaticEvilEyeButtonPreview,
  StaticAquaButtonPreview,
  StaticFrameButtonPreview,
  StaticHighlightButtonPreview,
  StaticConfettiButtonPreview,
  StaticAshBurstButtonPreview,
  StaticDontPressButtonPreview,
  StaticCommandButtonPreview,
  StaticCopyButtonPreview,
  StaticClickPowerUpPreview,
  StaticPillButtonPreview,
  StaticDemonicButtonPreview,
  StaticChromeButtonPreview,
  StaticGridButtonPreview,
  StaticMinimalButtonPreview,
  StaticMoviePassButtonPreview,
  StaticShinyButtonPreview,
  StaticStickyButtonPreview,
  StaticThreeDButtonPreview,
  StaticTrollButtonPreview,
} from "./static";

const dialButtonPreviews: Record<string, ComponentType> = {
  "reveal-button": RevealButtonPreview,
  "command-button": CommandButtonPreview,
  "copy-button": CopyButtonPreview,
  "click-powerup": ClickPowerUpPreview,
  "dither-button": DitherButtonPreview,
  "hold-button": HoldButtonPreview,
  "demonic-button": DemonicButtonPreview,
  "evil-eye-button": EvilEyeButtonPreview,
  "aqua-button": AquaButtonPreview,
  "brutal-button": BrutalButtonPreview,
  "chrome-button": ChromeButtonPreview,
  "frame-button": FrameButtonPreview,
  "glitch-button": GlitchButtonPreview,
  "grid-button": GridButtonPreview,
  "highlight-button": HighlightButtonPreview,
  minimal: MinimalButtonPreview,
  "movie-pass": MoviePassButtonPreview,
  "shiny-button": ShinyButtonPreview,
  sticky: StickyButtonPreview,
  "3d-button": ThreeDButtonPreview,
  "troll-button": TrollButtonPreview,
  "captcha-button": CaptchaButtonPreview,
  "doubt-button": DoubtButtonPreview,
  "slide-to-detonate": SlideToDetonatePreview,
  "morph-status-button": MorphStatusButtonPreview,
  "cooldown-button": CooldownButtonPreview,
  "pill-button": PillButtonPreview,
  "confetti-button": ConfettiButtonPreview,
  "hold-confirm-button": HoldConfirmButtonPreview,
  "dont-press-button": DontPressButtonPreview,
  "ash-burst-button": AshBurstButtonPreview,
};

const staticButtonPreviews: Record<string, ComponentType> = {
  "reveal-button": StaticRevealButtonPreview,
  "command-button": StaticCommandButtonPreview,
  "copy-button": StaticCopyButtonPreview,
  "click-powerup": StaticClickPowerUpPreview,
  "dither-button": StaticDitherButtonPreview,
  "hold-button": StaticHoldButtonPreview,
  "demonic-button": StaticDemonicButtonPreview,
  "evil-eye-button": StaticEvilEyeButtonPreview,
  "aqua-button": StaticAquaButtonPreview,
  "brutal-button": StaticBrutalButtonPreview,
  "chrome-button": StaticChromeButtonPreview,
  "frame-button": StaticFrameButtonPreview,
  "glitch-button": StaticGlitchButtonPreview,
  "grid-button": StaticGridButtonPreview,
  "highlight-button": StaticHighlightButtonPreview,
  minimal: StaticMinimalButtonPreview,
  "movie-pass": StaticMoviePassButtonPreview,
  "shiny-button": StaticShinyButtonPreview,
  sticky: StaticStickyButtonPreview,
  "3d-button": StaticThreeDButtonPreview,
  "troll-button": StaticTrollButtonPreview,
  "captcha-button": StaticCaptchaButtonPreview,
  "doubt-button": StaticDoubtButtonPreview,
  "slide-to-detonate": StaticSlideToDetonatePreview,
  "morph-status-button": StaticMorphStatusButtonPreview,
  "cooldown-button": StaticCooldownButtonPreview,
  "pill-button": StaticPillButtonPreview,
  "confetti-button": StaticConfettiButtonPreview,
  "hold-confirm-button": StaticHoldConfirmButtonPreview,
  "dont-press-button": StaticDontPressButtonPreview,
  "ash-burst-button": StaticAshBurstButtonPreview,
};

export function ButtonPreview({
  registryName,
  dial = false,
}: {
  registryName: string;
  dial?: boolean;
}) {
  const map = dial ? dialButtonPreviews : staticButtonPreviews;
  const Preview = map[registryName];
  if (!Preview) return null;
  return <Preview />;
}